services:
  yoctocontainer:
    image: petalinuxcontainer
    container_name: petalinuxcontainer
    hostname: petalinuxcontainer
    stdin_open: true
    tty: true

    volumes:
      - .:/home/xilinx/work
      - ../bin:/home/xilinx/bin
      - /opt/xilinx/2025.2/Petalinux:/opt/xilinx/2025.2/Petalinux
